// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7T5NRL-Rpojdi-8ntAGyc8PI_4C0aB8',
    appId: '1:165411154671:web:a72bddc22da1218229091a',
    messagingSenderId: '165411154671',
    projectId: 'tresdet-478dd',
    authDomain: 'tresdet-478dd.firebaseapp.com',
    databaseURL: 'https://tresdet-478dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tresdet-478dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbpmDyopJfqL_JN5rFSC-onDGJjcLLJ40',
    appId: '1:165411154671:android:422cf1f64143411f29091a',
    messagingSenderId: '165411154671',
    projectId: 'tresdet-478dd',
    databaseURL: 'https://tresdet-478dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tresdet-478dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACFTftaauWPKbYkIBITFTRTpuxEze0Blo',
    appId: '1:165411154671:ios:e68a611b847e5cd129091a',
    messagingSenderId: '165411154671',
    projectId: 'tresdet-478dd',
    databaseURL: 'https://tresdet-478dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tresdet-478dd.appspot.com',
    iosClientId: '165411154671-9pg887ud34k8f6uo1q8dluen2h1k9i4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.tresDet',
  );
}
